nb_images: 10
output_dir: "/home/eloi/workspace/sandbox/toy-shapes-generation/images"
generator:
  _target_: generator.SimpleGenerator
  size: 256
  can_overlap: False
  can_go_out: False
  can_rotate: True
  pick_shape_once: True
  min_relative_size: null
  max_relative_size: null
  possible_relative_sizes: [0.05, 0.1, 0.15]
  possible_angles: null