nb_images: 10
output_dir: "/home/eloi/workspace/sandbox/toy-shapes-generation/images"
generator:
  _target_: generator.SimpleGenerator
  size: 64
  can_overlap: True
  can_go_out: False
  can_rotate: False
  min_size: 0.1
  max_size: 0.3